language: node_js
node_js:
- node
before_deploy: npm run build
deploy:
  provider: firebase
  token:
    secure: "OrfENjYyfpVV5Lc1YDIInonRBxgHyaJlFsgQYb+sAhd99ORb9bc8p1QzL3qcpi3nDASWiFF7pXCzhVFXtU9eZzKqnXPlTmh9X99ANgWvGcvc9xEiTVnHTHvquzysqvV1YGCvH1vfz0Dyt8KJIsBHAlzFhujmmHCYiu7GLKBN0+4TxAL1E72q3QzgXc69olnAxAatDWcPdSUH4Z2/4ix/a921pzK4NkYyWrIJkE+EjUfrBiWnw9u0G5ZhFc3TveVWqMZPkG6k/rFf5anDfH8I7tHjK8azEtL82m+IRTl4JbDOT0rRhrvjkgswSkiQlwJAll3cUCYp6jGcXPNlbkuu6Zz3eiu669a7BMBS47lboQOYzqRHptoqYbKJSGaNq9dBaWzvddxVZF26mgcPHFdD83YDbOcMIb1kQxsJZkuDTzNaxXjH0MeSCZ0OG8T0uLBK9BrgiZL/kRdeactEziAEPlji2a/2JEtjRCICmsodVWZcW8P6DzFrgSOu5IeYVOkcMCOl0ra8v3H48knfF/AvPa6T62UE8IFlZ/oeweOtyzsbt7QCrLY83EWKMmfJ66Sn4PV6KdH1lO8rSU3hOkVSY6jZOIO0OnDmmoJ3GCxViy1LFgHcx13PV+5wLca3QOqaLCBZzdxseunA316p/7hcdkSwog7K/7NXAXu1uPXPVw0="
  skip_cleanup: true
  project: "bagdrop-eddd8"